trigger:
- master

variables:
  azureSubscriptionEndpoint: Project3
  azureContainerRegistry: revprojectfactory.azurecr.io
  azureResourceGroup: Project3
  kubernetesCluster: Project3Cluster

stages:
- stage: Build
  jobs: 
  - job: BuildJob
    displayName: Job Building
    workspace:
      clean: outputs
    steps: 
    - script: |
        echo "Building Project..."
        sh 'mvn package -DskipTests=true -Dcheckstyle.skip=true'
        echo "Finished Building Project"
- stage: Test
  jobs:
  - job: TestProject
    displayName: Project Testing
    steps:
    - script: |
        echo "Testing Project..."
        sh 'mvn test -Dcheckstyle.skip=true'
        echo "Finished Testing Project"
# - stage: Install Helm
#   jobs:
#   - job: InstallHelm
#     displayName: Install Helm Chart
#     dependsOn: Project Testing
#     steps:
#     - script: echo "Installing Helm Chart..."
#     - task: HelmInstaller@1
#       displayName: Helm Installer
#       inputs:
#         HelmVersionToInstall: latest
- stage: Deploy  
  jobs:
  - deployment:
    displayName: Project Deployment
    environment: 'Project3Cluster'
    strategy:
      runOnce:
          deploy:
            steps: 
            - script: echo "Deploying Project..."
            - task: HelmDeploy@0
              displayName: Helm Deployment
              inputs:
                connectionType: Azure Resource Manager
                azureSubscriptionEndpoint: ${azureSubscriptionEndpoint}
                azureResourceGroup: ${azureResourceGroup}
                kubernetesCluster: ${kubernetesCluster}
#               command: install
#               chartType: FilePath
#               chartPath: Application/charts/sampleapp
            - script: echo "Finished Deploying Project"